apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .Orchestrator.Name }}-rolebinding
  namespace: {{ .Orchestrator.Namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Orchestrator.Name }}-serviceaccount
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ .Orchestrator.Name }}-role