apiVersion: v1
kind: Service
metadata:
  name: {{.Orchestrator.Name}}-service
  namespace: {{.Orchestrator.Namespace}}
  labels:
    app: {{.Orchestrator.Name}}
    component: {{.Orchestrator.Name}}
    app.kubernetes.io/instance: {{.Orchestrator.Name}}
    app.kubernetes.io/name: {{.Orchestrator.Name}}
    app.kubernetes.io/part-of: trustyai
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: http
      protocol: TCP
      port: 8033
      targetPort: 8033
    - name: health
      protocol: TCP
      port: 8034
      targetPort: 8034
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: {{.Orchestrator.Name}}
    component: {{.Orchestrator.Name}}
    app.kubernetes.io/instance: {{.Orchestrator.Name}}
    app.kubernetes.io/name: {{.Orchestrator.Name}}
    app.kubernetes.io/part-of: trustyai
