apiVersion: v1
kind: Service
metadata:
  name: {{.Name}}-service
  namespace: {{.Namespace}}
  labels:
    app: {{.Name}}
    component: {{.Name}}
    app.kubernetes.io/instance: {{.Name}}
    app.kubernetes.io/name: {{.Name}}
    app.kubernetes.io/part-of: trustyai
    app.kubernetes.io/version: {{.Version}}
spec:
  ipFamilies:
    - IPv4
  ports:
    - name: http
      protocol: TCP
      port: 8033
      targetPort: 8033
    - name: health
      protocol: TCP
      port: 8034
      targetPort: 8034
  internalTrafficPolicy: Cluster
  type: ClusterIP
  ipFamilyPolicy: SingleStack
  sessionAffinity: None
  selector:
    app: {{.Name}}
    component: {{.Name}}
    app.kubernetes.io/instance: {{.Name}}
    app.kubernetes.io/name: {{.Name}}
    app.kubernetes.io/part-of: trustyai
    app.kubernetes.io/version: {{.Version}}
